# have a look at http://www.pwills.com/posts/2017/12/20/website.html for font size change
title: Data Science Portfolio
email: adin786@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: adin786
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _portfolio

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Azam Din"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data Scientist and Analyst with a Mechanical Engineering background"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://adin786.github.io"
    # - label: "Twitter"
      # icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adin786"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/azam-din"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adin786"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/azam-din"
    - label: "CV download"
      icon: "fab fa-fw fa-linkedin"
      url: "https://github.com/adin786/adin786.github.io/blob/main/assets/files/CV%20-%20Azam%20Din.pdf?raw=true"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: true
      classes: wide
      share: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
